version: '3'

services:

  db:
    image: postgres:10
    container_name: docker_petdb
    restart: always
    ports:
      - 127.0.0.1:2345:5432
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    env_file:
      - prod.env
      - local.env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_pet_api
    volumes:
      - ./:/app
    env_file:
      - prod.env
      - local.env
    ports:
    - 5000:5000
